### ISSUE TITLE
run helios issue  NameError: name 'extract_value' is not defined

### ISSUE THREAD

**Issue by aall1230** [sparcians/map#465]
I have completed the steps to build the Sparta framework components:

cd sparta && mkdir release && cd release
cmake -DCMAKE_BUILD_TYPE=Release ..
make
cmake --install . --prefix $CONDA_PREFIX
I have also completed the steps to build the Helios/Argos transaction viewer:

cd helios && mkdir release && cd release
cmake -DCMAKE_BUILD_TYPE=Release ..
make
cmake --install . --prefix $CONDA_PREFIX
However, when I try to run the pythonw ${MAP}/helios/pipeViewer/pipe_view/argos.py --database pipeout_ --layout-file cpu_layout.alf command, I encounter an error. 

pythonw  ../../../../helios/pipeViewer/pipe_view/argos.py --database pipeout_ --layout-file cpu_layout.alf
INFO: looking for  /Users/liyang/opt/miniconda3/envs/sparta2/bin/transactionsearch
transaction search initialized: you will be able to use search.
Using: /Users/liyang/opt/miniconda3/envs/sparta2/bin/transactionsearch
Traceback (most recent call last):
  File "/Users/liyang/YangL/sparta/map/sparta/release/example/CoreModel/../../../../helios/pipeViewer/pipe_view/argos.py", line 45, in <module>
    from pipe_view.model.workspace import Workspace  # noqa: E402
  File "/Users/liyang/opt/miniconda3/envs/sparta2/lib/python3.10/site-packages/pipe_view/model/workspace.py", line 15, in <module>
    from ..gui.layout_frame import Layout_Frame
  File "/Users/liyang/opt/miniconda3/envs/sparta2/lib/python3.10/site-packages/pipe_view/gui/layout_frame.py", line 17, in <module>
    from .layout_canvas import Layout_Canvas
  File "/Users/liyang/opt/miniconda3/envs/sparta2/lib/python3.10/site-packages/pipe_view/gui/layout_canvas.py", line 27, in <module>
    from .. import core
  File "pipe_view/core/src/core.pyx", line 11, in init pipe_view.core
NameError: name 'extract_value' is not defined

**Comment by klingaard** [comment]
This recently popped up in an internal build of Sparta as well and it was determined to be either a "bug" in the newest cython or an issue in the glue code (didn't track it down).

In your conda (assuming you're using conda) environment, try installing an older version of cython:
```
conda activate sparta
pip install Cython=0.29.33
```
We need to force the cython version in the conda setup, but haven't had a moment to do so.

**Comment by aall1230** [comment]
That is great. Thank you very much.

**Comment by lhtin** [comment]
The same problem occurs when using python 3.10.13. 

```
(sparta) ➜  release git:(master) python ../../map/helios/pipeViewer/pipe_view/argos.py -h
INFO: looking for  /work/home/lding/miniconda3/envs/sparta/bin/transactionsearch
transaction search initialized: you will be able to use search.
Using: /work/home/lding/miniconda3/envs/sparta/bin/transactionsearch
Traceback (most recent call last):
  File "/work/home/lding/open-source/model/riscv-perf-model/release/../../map/helios/pipeViewer/pipe_view/argos.py", line 47, in <module>
    from pipe_view.model.workspace import Workspace  # noqa: E402
  File "/work/home/lding/open-source/model/map/helios/pipeViewer/pipe_view/../pipe_view/model/workspace.py", line 15, in <module>
    from ..gui.layout_frame import Layout_Frame
  File "/work/home/lding/open-source/model/map/helios/pipeViewer/pipe_view/../pipe_view/gui/layout_frame.py", line 17, in <module>
    from .layout_canvas import Layout_Canvas
  File "/work/home/lding/open-source/model/map/helios/pipeViewer/pipe_view/../pipe_view/gui/layout_canvas.py", line 27, in <module>
    from .. import core
  File "pipe_view/core/src/core.pyx", line 11, in init pipe_view.core
NameError: name 'extract_value' is not defined
```

**Comment by lhtin** [comment]
Oh, got it, need to recompile Helios.

**Comment by klingaard** [comment]
Fixed in https://github.com/sparcians/map/pull/494
