### ISSUE TITLE
Pythonw complaining NameError: name 'extract_value' is not defined in pipe_view/core/src/core.pyx

### ISSUE THREAD

**Issue by furuame** [sparcians/map#490]
```
(sparta) ➜  pipe_view git:(master) ✗ pythonw argos.py
INFO: looking for  /opt/miniconda3/envs/sparta/bin/transactionsearch
transaction search initialized: you will be able to use search.
Using: /opt/miniconda3/envs/sparta/bin/transactionsearch
Traceback (most recent call last):
  File "/Users/zhen.wei/Software/map/helios/pipeViewer/pipe_view/argos.py", line 45, in <module>
    from pipe_view.model.workspace import Workspace  # noqa: E402
  File "/opt/miniconda3/envs/sparta/lib/python3.10/site-packages/pipe_view/model/workspace.py", line 15, in <module>
    from ..gui.layout_frame import Layout_Frame
  File "/opt/miniconda3/envs/sparta/lib/python3.10/site-packages/pipe_view/gui/layout_frame.py", line 17, in <module>
    from .layout_canvas import Layout_Canvas
  File "/opt/miniconda3/envs/sparta/lib/python3.10/site-packages/pipe_view/gui/layout_canvas.py", line 27, in <module>
    from .. import core
  File "pipe_view/core/src/core.pyx", line 11, in init pipe_view.core
NameError: name 'extract_value' is not defined
```

I don’t know why this bug comes up when I installed a new conda environment recently.

My solution was: moving the definition of `extract_value` in `core.pyx` beyond the definition of `EXPR_NAMESPACE`. And that trick works. Wondering how that worked before ... Do you have any thoughts? If that change makes sense to you (@klingaard @bdutro), I can file a PR for this.

**Comment by klingaard** [comment]
Yeah, this is the same issue as https://github.com/sparcians/map/issues/465.  In a nutshell, the newest version of `cython` broke us.

**Comment by furuame** [comment]
Thanks! I’ll see if I can enforce the cython version in Conda

**Comment by klingaard** [comment]
Fixed in https://github.com/sparcians/map/pull/494
